name: Challenges-plugin
version: '${version}'

main: tv.sparkening.challengesplugin.ChallengesPlugin
api-version: '26.1.2'
load: POSTWORLD

commands:
  challenge:
    description: Opens the challenge selector menu.
    usage: /challenge

  timer:
    description: allows control over the timer
    usage: /timer
